# Generated by Django 4.1.1 on 2023-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=-1091, max_length=100),
            preserve_default=False,
        ),
    ]
